### ISSUE TITLE
Uncaught Exception: String could not be parsed 

### ISSUE THREAD

**Issue by ghost** [ProjectMyst/roundcube-plesk#1]
[28-Jul-2022 13:11:41 UTC] PHP Fatal error:  Uncaught Exception: String could not be parsed as XML in /var/www/vhosts/.nl/email..nl/plugins/plesk/ApiCalls.php:37
Stack trace:
#0 /var/www/vhosts/.nl/email..nl/plugins/plesk/ApiCalls.php(37): SimpleXMLElement->__construct()
#1 /var/www/vhosts/.nl/email..nl/plugins/plesk/plesk.php(89): include_once('...')
#2 /var/www/vhosts/.nl/email..nl/program/include/rcmail_output_html.php(1484): plesk->autoreply_html()
#3 [internal function]: rcmail_output_html->xml_command()
#4 /var/www/vhosts/.nl/email..nl/program/include/rcmail_output_html.php(1322): preg_replace_callback()
#5 /var/www/vhosts/.nl/email..nl/program/include/rcmail_output_html.php(825): rcmail_output_html->parse_xml()
#6 /var/www/vhosts/.nl/email..nl/program/include/rcmail_output_html.php(654): rcmail_output_html->parse()
#7 /var/www/vhosts/ypsilonwebdesign.nl/email..nl/plugins/plesk/plesk.php(62): rcmail_output_html->send()
#8 /var/www/vhosts/.nl/email..nl/program/lib/Roundcube/rcube_plugin_api.php(573): plesk->plesk_autoreply()
#9 /var/www/vhosts/.nl/email..nl/program/include/rcmail.php(248): rcube_plugin_api->exec_action()
#10 /var/www/vhosts/.nl/email..nl/index.php(283): rcmail->action_handler()
#11 {main}
  thrown in /var/www/vhosts/.nl/email..nl/plugins/plesk/ApiCalls.php on line 37

Hello, i have installed your plugin, but got a error in the log.

What can i do for you to debug the problem?

**Comment by ghost** [comment]
Sorry my mistake. It is working . Gooed work.
